apiVersion: v1
kind: Secret
metadata:
  name: my-dockerhub-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
#base64-encoded-contents-of-.docker/config.json-file
  .dockerconfigjson: |  #base64-encoded-contents-of-.docker/config.json-file
    ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewog
    ICAgICAgICJhdXRoIjogIk1IaDZaVHB5WW1seU1qYzFRQT09IiwgCiAgICAgICAgImVtYWlsIjog
    Im1vaGFtbWVkZC5lbGRlZWJAZ21haWwuY29tIgogICAgICB9CiAgICB9CiAgfQo=
#{{ .Files.Get "config.json" | b64enc | quote }}