apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pv-claim
  labels:
    app: {{ .Release.Name }}-mysql-pv-claim #{{ include "app-stack.name" . }}
    
#  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
#    "helm.sh/hook": pre-install
#    "helm.sh/hook-weight": "-5"
#    "helm.sh/hook-delete-policy": hook-succeeded

  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}