apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-phpmyadmin-service
  labels:
    app: {{ .Release.Name }}-phpmyadmin
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-phpmyadmin
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.phpMyAdmin.svcPort }}
      targetPort: 80
  type: {{ .Values.phpMyAdmin.svcType }}