apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask-app
  labels:
    app: {{ .Release.Name }}-flask-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.flask.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flask-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flask-app
    spec:
      imagePullSecrets:
      - name: my-dockerhub-secret
      containers:
        - name: {{ .Release.Name }}-flask-app
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          image: "{{ .Values.flask.account }}/{{ .Values.flask.imageRepository }}"
          resources: {}
      restartPolicy: Always