apiVersion: v1
clusters:
- cluster:
# ca.crt base64
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJME1ERXlOVEV6TVRFME5Gb1hEVE0wTURFeU16RXpNVEUwTkZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnIwCklGbElrSm40SG5TZkVLSXB2TSswTXZWZEowZmExYm1wZUNsMWx1bW5janJGNFkxRGNzUkI2LytnWG1tTGJ4YnoKZDN1Y09JQnBjeXZsSytVVnUxbGlFNkFIeWo4Y1BIS2c1b3ZRNllDMk9wVkc4azRpVTFoQzNoTndRT0VrK2NaTAoxR3ZFaEVKQmNoVlVSVmxTZWxVVm1yVTllZXY0VnFaNHorNWdyTUswbTNnaHNVa0xHck9mYVFEQXRCeHBacnF2Cmozb2xJNmpFVlNuRDQyVHdHWHllVzA2bDY0bFFoNDhYdUZnVVJKZGNQV3E3VG41dlB1ejR3YjBPRE5welVXeFoKUkVaWWF6Q21Xc09EQ0ZUR0wxamhUNUxIaUlCdkwrZWM5dHhROW14QVhnZmJqNGZSc3NaYm85bjZ2c0R5YnpmRgpvVEJLY3VLNDBBd1ZBcG5TYjgwQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJTSzNiSFVMWVY3NzBxK3YxejdHdVBuWmtvQTl6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFDNE1MTWZjKwpjNElwUnNQS2ZmTnFWN0Z6Y1RNQVFJaC8rdEJybnBsT2FFRkhVcytmekE4WnpReU9BS3ZWMElNRVdHcjdaUmVaCkxPT2JDU2FxdHp6VUJwK1Y3N0g1bzllaThyNi8zSUtjK2swdXlLd3pIRTdKVVFWZzVaRnNoQm5WY3NNelQ4T0kKdGRVZkcvMHBOWnVJS0hERlBOemlTVGtZZGVOSFMyeXpxaElBdkdJMG1KdDlIUmM2cGw3RE9zM3VRQjlqK1RNZwpDa0RycVdzK2dKdkFNdmJGT1Z5U2t5TWl0Wnh3d2JSZDN1Uzhrc2Q4NnFvRUJPVkJldEJaNTZMTjRjdmtBMHdUCk1vZWZwdTBDWUVYVTZzRG5SWFBXUkwzODRoQjhGdnRwNUJlOXdRL1VsdmVsSjAwaDZWSVFlOVdmdG4zbjhLaTkKNVR3dTN6aVpYdXpra3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    extensions:
    - extension:
        last-update: Wed, 17 Jan 2024 01:47:02 EET
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: my-apps
    user: gitlab-sa
  name: gitlab-context
current-context: gitlab-context
kind: Config
preferences: {}
users:
- name: gitlab-sa
  user:
# gitlab-sa token base64
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ild1YWZhMVNJdFR6bzVrdVVoWmZ1aFRaWEdKUjlvUmhHaHFRMWk4ZXdMMFEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteS1hcHBzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdpdGxhYi1zYS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJnaXRsYWItc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5NWQ0Mzc4Yy0xZTRhLTRkOGItYjA3NC0yMjMxYzBkMGYxNDUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bXktYXBwczpnaXRsYWItc2EifQ.QmCSFJJE1ln3X8MTrnVbBt4sc6kcHBSYkFHlrBklQz25DmVrBrnVxX3-uaQZO8x25hxMtshKox58hEIs8KQbQ2yoozRgnpHbfgRehCnusHg7GVqBn9AerBUW0UY9Jr6ieGgoZjXDHxk0wPw5rGlNdYg3boaMtBlSU0VSjfLpTds6LQhtyN6Rux8u-577W4y1KnZ5A1cxbx4-Ihh4utuSxAIbIn4tP1gt2VsSAw4CVNaRG7y3LW81b2lVGJQwgwzrWidr7outJVOaP4zJ_M3LExkxUlbf0uMf_RTgF-aDtAHVJCMrbeDCX37opwlyksUTFk-UleZ-t7xnB_icZhJQug 

